[package]
name = "passwd-simulate"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
base64ct = "1.6.0"
digest = "0.10.7"
md-5 = "0.10.5"
rand = "0.8.5"
rpassword = "7.2.0"
sha2 = "0.10.6"
